FROM platoon-centos
MAINTAINER Greg Fullard
USER root

# Install Java
RUN yum install -y java

# Copy the readme file into the image
COPY platoon-openjdk-readme.txt /home/platoon/platoon-openjdk-readme.txt
