FROM argilla-centos
MAINTAINER Greg Fullard
USER root

# Install Java
RUN yum install -y java

# Copy the readme file into the image
COPY argilla-openjdk-readme.md /home/argilla/argilla-openjdk-readme.md
